services:
  postgres:
    image: 'postgres:17.4'
    environment:
      - 'POSTGRES_USER=postgresql'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=arthub'
    ports:
      - '25432:5432'
    #labels:
    #  org.springframework.boot.jdbc.parameters: 'ssl=true&sslmode=require'
